name: Update Ladder

on:
  issues:
    types: [opened, edited, labeled]
  workflow_dispatch:

jobs:
  update-ladder:
    if: contains(github.event.issue.labels.*.name, 'benchmark') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Generate JSON data
      run: npm run generate-data
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: npm run build

    - name: Copy JSON to dist
      run: cp ladder_data.json dist/

    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add -A
        git commit -m "Update Ladder data" || echo "No changes to commit"
        git push || echo "No changes to push"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        force_orphan: true
