name: Update JSON

on:
  issues:
    types: [opened, edited, labeled]
  workflow_dispatch:

jobs:
  update-json:
    if: contains(github.event.issue.labels.*.name, 'benchmark') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Check for package-lock.json
      id: check-lock
      run: |
        if [ -f "package-lock.json" ]; then
          echo "::set-output name=exists::true"
        else
          echo "::set-output name=exists::false"
        fi

    - name: Install dependencies (with package-lock.json)
      if: steps.check-lock.outputs.exists == 'true'
      run: npm ci

    - name: Install dependencies (without package-lock.json)
      if: steps.check-lock.outputs.exists == 'false'
      run: npm install

    - name: Generate JSON data
      run: npm run generate-data
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add -A
        git commit -m "Update JSON data" || exit 0
        git push
