name: Update Ladder

on:
  issues:
    types: [opened, edited]
  workflow_dispatch: # 允许手动触发

jobs:
  update-ladder:
    if: contains(github.event.issue.labels.*.name, 'benchmark')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: |
          npm install
          npm ci
      - name: Build
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
